language: php

php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.0 version
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

matrix:
  fast_finish: true
